package com.mulesoft.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-10-24T10:33:15.904-07:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://examples.mulesoft.com/", name = "AccountUpdate")
@XmlSeeAlso({ObjectFactory.class})
public interface AccountUpdate {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateAccount", targetNamespace = "http://examples.mulesoft.com/", className = "com.mulesoft.example.UpdateAccount")
    @WebMethod
    @ResponseWrapper(localName = "updateAccountResponse", targetNamespace = "http://examples.mulesoft.com/", className = "com.mulesoft.example.UpdateAccountResponse")
    public java.lang.String updateAccount(
        @WebParam(name = "accountNameId", targetNamespace = "")
        java.lang.String accountNameId
    ) throws Exception_Exception;
}
