
package com.mulesoft.example;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-10-24T10:33:15.899-07:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "Exception", targetNamespace = "http://examples.mulesoft.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.mulesoft.example.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.mulesoft.example.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.mulesoft.example.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.mulesoft.example.Exception getFaultInfo() {
        return this.exception;
    }
}
